// <auto-generated />
namespace Lab6_ASPNET.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class Rating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rating));
        
        string IMigrationMetadata.Id
        {
            get { return "201507302329159_Rating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
